__all__ = ("CancelledError",)


class CancelledError(Exception):
    pass
